# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

default_stages:
  - pre-commit

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/crate-ci/typos
  rev: v1.32.0
  hooks:
    - id: typos
      args: ["--config", ".typos.toml"]
      exclude: |
        (?x)^(
          ^\.typos\.toml$
        )$
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.0
  hooks:
    - id: commitizen
      stages: [commit-msg]
